import * as synapse from "@distilled.cloud/azure/synapse";
import * as Effect from "effect/Effect";
import type * as Redacted from "effect/Redacted";
import { Unowned } from "../../AdoptPolicy.ts";
import { isResolved } from "../../Diff.ts";
import * as Provider from "../../Provider.ts";
import { Resource } from "../../Resource.ts";
import {
  desiredTags,
  ensureRegistered,
  hasAnyAlchemyTag,
  ignoreNotFound,
  isOwned,
  requireSinglePage,
  resourceGroupOf,
  tagsDiffer,
  userTags,
  waitForProvisioned,
  waitUntilGone,
} from "../Arm.ts";
import { AzureEnvironment } from "../Environment.ts";
import type { Providers } from "../Providers.ts";
import {
  createDnsName,
  fieldsMatch,
  getWorkspace,
  lower,
  sameSecret,
  secretFingerprint,
} from "./common.ts";

/** The workspace's default ADLS Gen2 file system. */
export interface WorkspaceDataLakeStorage {
  /**
   * DFS endpoint of the storage account, e.g.
   * `https://{account}.dfs.core.windows.net`. The account must have a
   * hierarchical namespace.
   */
  accountUrl: string;
  /** Name of the file system (blob container) in the account. */
  filesystem: string;
  /** ARM resource ID of the storage account. */
  resourceId?: string;
  /** Create a managed private endpoint to the account (managed VNet only). */
  createManagedPrivateEndpoint?: boolean;
}

/** Managed identities assigned to the workspace. */
export interface WorkspaceIdentity {
  /** Identity type. */
  type: "None" | "SystemAssigned" | "SystemAssigned,UserAssigned";
  /** ARM resource IDs of user-assigned identities. */
  userAssignedIdentityIds?: string[];
}

/** Customer-managed key used to double-encrypt the workspace. */
export interface WorkspaceCustomerManagedKey {
  /** Name of the workspace key that wraps the data encryption key. */
  keyName: string;
  /** Key Vault key URL (without version), e.g. `https://{vault}.vault.azure.net/keys/{key}`. */
  keyVaultUrl: string;
  /**
   * ARM resource ID of a user-assigned identity used to access the key.
   * @default the workspace's system-assigned identity
   */
  userAssignedIdentity?: string;
}

/** Git integration for Synapse Studio. */
export interface WorkspaceRepositoryConfiguration {
  /** `WorkspaceVSTSConfiguration` (Azure DevOps) or `WorkspaceGitHubConfiguration`. */
  type: "WorkspaceVSTSConfiguration" | "WorkspaceGitHubConfiguration";
  /** GitHub Enterprise host name, e.g. `https://github.mydomain.com`. */
  hostName?: string;
  /** Account (organization) name. */
  accountName: string;
  /** Azure DevOps project name. */
  projectName?: string;
  /** Repository name. */
  repositoryName: string;
  /** Collaboration branch. */
  collaborationBranch: string;
  /** Root folder in the repository. */
  rootFolder: string;
  /** Azure DevOps tenant ID. */
  tenantId?: string;
}

export interface WorkspaceProps {
  /** Resource group the workspace is created in. Changing it replaces the workspace. */
  resourceGroup: string;
  /**
   * Globally unique workspace name: 1-50 lowercase letters, digits, and
   * hyphens, starting and ending with a letter or digit. If omitted, a
   * unique name is generated from the app, stage, and logical ID. Changing
   * it replaces the workspace.
   */
  name?: string;
  /**
   * Azure location of the workspace. Changing it replaces the workspace.
   * @default the `Azure.Location` layer, else the profile location, else `eastus`
   */
  location?: string;
  /**
   * Default ADLS Gen2 file system used by Spark and serverless SQL.
   * Changing it replaces the workspace.
   */
  defaultDataLakeStorage: WorkspaceDataLakeStorage;
  /**
   * SQL administrator login of the built-in SQL endpoints. Cannot be
   * changed after creation, so changing it replaces the workspace.
   */
  sqlAdministratorLogin?: string;
  /**
   * SQL administrator password. Write-only: Azure never returns it, so
   * Alchemy stores a salted fingerprint and only re-sends it when it
   * changes.
   */
  sqlAdministratorLoginPassword?: Redacted.Redacted<string>;
  /**
   * Name of the managed resource group Synapse creates for its internal
   * resources. Changing it replaces the workspace.
   * @default generated by Azure (`synapseworkspace-managedrg-<guid>`)
   */
  managedResourceGroupName?: string;
  /**
   * Run Spark and pipelines in a Synapse-managed virtual network. Changing
   * it replaces the workspace.
   * @default false
   */
  managedVirtualNetwork?: boolean;
  /**
   * Block outbound traffic from the managed virtual network except to
   * approved targets. Requires `managedVirtualNetwork`. Changing it
   * replaces the workspace.
   * @default false
   */
  preventDataExfiltration?: boolean;
  /**
   * Entra tenants the managed virtual network may link to when data
   * exfiltration protection is on.
   */
  allowedAadTenantIdsForLinking?: string[];
  /**
   * Subnet for Spark compute (legacy VNet injection). Changing it replaces
   * the workspace.
   */
  computeSubnetId?: string;
  /**
   * Managed identities assigned to the workspace.
   * @default `{ type: "SystemAssigned" }`
   */
  identity?: WorkspaceIdentity;
  /**
   * Whether the workspace endpoints accept public traffic.
   * @default Azure's default (`Enabled`)
   */
  publicNetworkAccess?: "Enabled" | "Disabled";
  /**
   * Double-encrypt the workspace with a customer-managed key. Only applied
   * at creation; changing it replaces the workspace. The workspace stays
   * pending until the key is activated with `Azure.Synapse.WorkspaceKey`.
   */
  customerManagedKey?: WorkspaceCustomerManagedKey;
  /** ARM resource ID of a Microsoft Purview account to connect. */
  purviewResourceId?: string;
  /** Git integration for Synapse Studio. */
  repositoryConfiguration?: WorkspaceRepositoryConfiguration;
  /**
   * Object ID of the initial workspace administrator. Only applied at
   * creation.
   */
  initialWorkspaceAdminObjectId?: string;
  /**
   * Allow only Microsoft Entra authentication at creation. Manage it
   * afterwards with `Azure.Synapse.AzureADOnlyAuthentication`.
   */
  azureADOnlyAuthentication?: boolean;
  /**
   * Let trusted Azure services bypass the workspace firewall. Only applied
   * at creation.
   */
  trustedServiceBypassEnabled?: boolean;
  /**
   * User tags. Alchemy ownership tags (`alchemy::stack`, `alchemy::stage`,
   * `alchemy::id`) are merged in automatically.
   */
  tags?: Record<string, string>;
}

/** Endpoints of a Synapse workspace. */
export interface WorkspaceConnectivityEndpoints {
  /** Synapse Studio URL. */
  web: string | undefined;
  /** Development endpoint, e.g. `https://{name}.dev.azuresynapse.net`. */
  dev: string | undefined;
  /** Dedicated SQL endpoint, e.g. `{name}.sql.azuresynapse.net`. */
  sql: string | undefined;
  /** Serverless SQL endpoint, e.g. `{name}-ondemand.sql.azuresynapse.net`. */
  sqlOnDemand: string | undefined;
}

export interface Workspace extends Resource<
  "Azure.Synapse.Workspace",
  WorkspaceProps,
  {
    /** Name of the workspace. */
    workspaceName: string;
    /** ARM resource ID of the workspace. */
    workspaceId: string;
    /** Resource group that holds the workspace. */
    resourceGroup: string;
    /** Location of the workspace. */
    location: string;
    /** Unique identifier (GUID) of the workspace. */
    workspaceUID: string | undefined;
    /** Workspace endpoints. */
    connectivityEndpoints: WorkspaceConnectivityEndpoints;
    /** Managed resource group created by Synapse. */
    managedResourceGroupName: string | undefined;
    /** SQL administrator login. */
    sqlAdministratorLogin: string | undefined;
    /** Whether the workspace endpoints accept public traffic. */
    publicNetworkAccess: string | undefined;
    /** Object ID of the system-assigned identity. */
    principalId: string | undefined;
    /** Tenant of the system-assigned identity. */
    tenantId: string | undefined;
    /** Salted fingerprint of the last SQL administrator password Alchemy set. */
    passwordFingerprint: Redacted.Redacted<string> | undefined;
    /** User tags (Alchemy ownership tags stripped). */
    tags: Record<string, string>;
  },
  never,
  Providers
> {}

/**
 * An Azure Synapse Analytics workspace — the boundary for Spark pools,
 * dedicated and serverless SQL pools, pipelines, and Synapse Studio. The
 * workspace itself and its serverless SQL endpoint cost nothing while
 * idle.
 *
 * A workspace needs a default ADLS Gen2 file system (a storage account
 * with `isHnsEnabled: true` and a container). Grant the workspace identity
 * `Storage Blob Data Contributor` on the account so Spark and serverless
 * SQL can read and write it. Deleting the workspace also deletes its
 * managed resource group.
 *
 * @see https://learn.microsoft.com/azure/synapse-analytics/overview-what-is
 *
 * ### Creating a Workspace
 * **Example:** Workspace on a Data Lake file system
 * ```typescript
 * const group = yield* Azure.Resources.ResourceGroup("analytics");
 * const lake = yield* Azure.Storage.StorageAccount("lake", {
 *   resourceGroup: group.resourceGroupName,
 *   isHnsEnabled: true,
 * });
 * const fs = yield* Azure.Storage.BlobContainer("fs", {
 *   resourceGroup: group.resourceGroupName,
 *   storageAccount: lake.storageAccountName,
 * });
 * const workspace = yield* Azure.Synapse.Workspace("ws", {
 *   resourceGroup: group.resourceGroupName,
 *   defaultDataLakeStorage: {
 *     accountUrl: lake.primaryEndpoints.dfs.as<string>(),
 *     filesystem: fs.containerName,
 *   },
 *   sqlAdministratorLogin: "sqladmin",
 *   sqlAdministratorLoginPassword: Redacted.make(password),
 * });
 * ```
 *
 * ### Network Isolation
 * **Example:** Managed virtual network with exfiltration protection
 * ```typescript
 * const workspace = yield* Azure.Synapse.Workspace("ws", {
 *   resourceGroup: group.resourceGroupName,
 *   defaultDataLakeStorage: {
 *     accountUrl: lake.primaryEndpoints.dfs.as<string>(),
 *     filesystem: fs.containerName,
 *   },
 *   managedVirtualNetwork: true,
 *   preventDataExfiltration: true,
 *   publicNetworkAccess: "Disabled",
 * });
 * ```
 *
 * @resource
 */
export const Workspace = Resource<Workspace>("Azure.Synapse.Workspace");

type ObservedWorkspace = synapse.GetWorkspaceResponse;

export const createWorkspaceName = (id: string) => createDnsName(id, 50);

const toAttrs = (
  resourceGroup: string,
  name: string,
  workspace: ObservedWorkspace,
  passwordFingerprint: Redacted.Redacted<string> | undefined,
): Workspace["Attributes"] => {
  const props = workspace.properties;
  const endpoints = props?.connectivityEndpoints;
  return {
    workspaceName: name,
    workspaceId: workspace.id ?? "",
    resourceGroup,
    location: workspace.location,
    workspaceUID: props?.workspaceUID,
    connectivityEndpoints: {
      web: endpoints?.web,
      dev: endpoints?.dev,
      sql: endpoints?.sql,
      sqlOnDemand: endpoints?.sqlOnDemand,
    },
    managedResourceGroupName: props?.managedResourceGroupName,
    sqlAdministratorLogin: props?.sqlAdministratorLogin,
    publicNetworkAccess: props?.publicNetworkAccess,
    principalId: workspace.identity?.principalId,
    tenantId: workspace.identity?.tenantId,
    passwordFingerprint,
    tags: userTags(workspace.tags),
  };
};

const desiredIdentity = (identity: WorkspaceIdentity | undefined) =>
  identity ?? { type: "SystemAssigned" as const };

const toIdentity = (identity: WorkspaceIdentity) => ({
  type: identity.type,
  userAssignedIdentities:
    identity.userAssignedIdentityIds === undefined
      ? undefined
      : Object.fromEntries(
          identity.userAssignedIdentityIds.map((id) => [id, {}]),
        ),
});

const identityDiffers = (
  observed: ObservedWorkspace["identity"],
  desired: WorkspaceIdentity,
) => {
  const observedType = (observed?.type ?? "None").replace(/\s/g, "");
  if (lower(observedType) !== lower(desired.type)) return true;
  const want = (desired.userAssignedIdentityIds ?? []).map(lower).sort();
  const have = Object.keys(observed?.userAssignedIdentities ?? {})
    .map(lower)
    .sort();
  return want.join(",") !== have.join(",");
};

const waitReady = (
  subscriptionId: string,
  resourceGroup: string,
  name: string,
  converged: (workspace: ObservedWorkspace) => boolean = () => true,
) =>
  waitForProvisioned(
    `synapse workspace ${name}`,
    getWorkspace(subscriptionId, resourceGroup, name),
    (workspace) =>
      converged(workspace)
        ? workspace.properties?.provisioningState
        : "Updating",
    { interval: "10 seconds", times: 90 },
  );

export const WorkspaceProvider = () =>
  Provider.succeed(Workspace, {
    stables: [
      "workspaceName",
      "workspaceId",
      "resourceGroup",
      "location",
      "workspaceUID",
      "connectivityEndpoints",
      "managedResourceGroupName",
      "sqlAdministratorLogin",
    ],

    list: Effect.fn(function* () {
      const { subscriptionId } = yield* AzureEnvironment.current;
      const page = yield* synapse
        .ListWorkspaces({ subscriptionId })
        .pipe(
          Effect.flatMap((page) => requireSinglePage("ListWorkspaces", page)),
        );
      return (page.value ?? []).flatMap((workspace) => {
        const group = resourceGroupOf(workspace.id);
        return hasAnyAlchemyTag(workspace.tags) &&
          group !== undefined &&
          workspace.name !== undefined
          ? [toAttrs(group, workspace.name, workspace, undefined)]
          : [];
      });
    }),

    diff: Effect.fn(function* ({ news, olds, output }) {
      if (!isResolved(news) || output === undefined) return undefined;
      const lake = news.defaultDataLakeStorage;
      const oldLake = olds?.defaultDataLakeStorage;
      if (
        lower(news.resourceGroup) !== lower(output.resourceGroup) ||
        (news.name !== undefined && news.name !== output.workspaceName) ||
        (news.location !== undefined &&
          lower(news.location) !== lower(output.location)) ||
        (news.sqlAdministratorLogin !== undefined &&
          output.sqlAdministratorLogin !== undefined &&
          news.sqlAdministratorLogin !== output.sqlAdministratorLogin) ||
        (news.managedResourceGroupName !== undefined &&
          output.managedResourceGroupName !== undefined &&
          lower(news.managedResourceGroupName) !==
            lower(output.managedResourceGroupName)) ||
        (oldLake !== undefined &&
          (lower(lake.accountUrl.replace(/\/$/, "")) !==
            lower(oldLake.accountUrl.replace(/\/$/, "")) ||
            lake.filesystem !== oldLake.filesystem)) ||
        (olds !== undefined &&
          ((news.managedVirtualNetwork ?? false) !==
            (olds.managedVirtualNetwork ?? false) ||
            (news.preventDataExfiltration ?? false) !==
              (olds.preventDataExfiltration ?? false) ||
            lower(news.computeSubnetId) !== lower(olds.computeSubnetId) ||
            !fieldsMatch(olds.customerManagedKey, news.customerManagedKey) ||
            !fieldsMatch(news.customerManagedKey, olds.customerManagedKey)))
      ) {
        return { action: "replace" } as const;
      }
      return undefined;
    }),

    read: Effect.fn(function* ({ id, olds, output }) {
      const { subscriptionId } = yield* AzureEnvironment.current;
      const resourceGroup = output?.resourceGroup ?? olds?.resourceGroup;
      if (resourceGroup === undefined) return undefined;
      const name =
        output?.workspaceName ?? olds?.name ?? (yield* createWorkspaceName(id));
      const observed = yield* getWorkspace(subscriptionId, resourceGroup, name);
      if (observed === undefined) return undefined;
      const attrs = toAttrs(
        resourceGroup,
        name,
        observed,
        output?.passwordFingerprint,
      );
      return (yield* isOwned(id, observed.tags)) ? attrs : Unowned(attrs);
    }),

    reconcile: Effect.fn(function* ({ id, news, output }) {
      const env = yield* AzureEnvironment.current;
      const { subscriptionId } = env;
      yield* ensureRegistered(subscriptionId, "Microsoft.Synapse");
      const resourceGroup = news.resourceGroup;
      const name =
        news.name ?? output?.workspaceName ?? (yield* createWorkspaceName(id));
      const location = news.location ?? output?.location ?? env.location;
      const tags = yield* desiredTags(id, news.tags);
      const identity = desiredIdentity(news.identity);
      const fingerprint = yield* secretFingerprint(
        `${resourceGroup}/${name}`,
        news.sqlAdministratorLoginPassword,
      );
      const where = {
        subscriptionId,
        resourceGroupName: resourceGroup,
        workspaceName: name,
      };
      const vnetSettings =
        news.preventDataExfiltration !== undefined ||
        news.allowedAadTenantIdsForLinking !== undefined
          ? {
              preventDataExfiltration: news.preventDataExfiltration,
              allowedAadTenantIdsForLinking: news.allowedAadTenantIdsForLinking,
            }
          : undefined;
      const repository =
        news.repositoryConfiguration === undefined
          ? undefined
          : { ...news.repositoryConfiguration };
      const purview =
        news.purviewResourceId === undefined
          ? undefined
          : { purviewResourceId: news.purviewResourceId };

      // Observe.
      let observed = yield* getWorkspace(subscriptionId, resourceGroup, name);

      // Ensure. Creation is a long-running operation carrying every
      // create-only setting and the write-only password.
      let passwordSent = false;
      if (observed === undefined) {
        const cmk = news.customerManagedKey;
        yield* synapse.WorkspacesCreateOrUpdate({
          ...where,
          location,
          tags,
          identity: toIdentity(identity),
          properties: {
            defaultDataLakeStorage: { ...news.defaultDataLakeStorage },
            sqlAdministratorLogin: news.sqlAdministratorLogin,
            sqlAdministratorLoginPassword: news.sqlAdministratorLoginPassword,
            managedResourceGroupName: news.managedResourceGroupName,
            managedVirtualNetwork: news.managedVirtualNetwork
              ? "default"
              : undefined,
            managedVirtualNetworkSettings: vnetSettings,
            virtualNetworkProfile:
              news.computeSubnetId === undefined
                ? undefined
                : { computeSubnetId: news.computeSubnetId },
            encryption:
              cmk === undefined
                ? undefined
                : {
                    cmk: {
                      key: { name: cmk.keyName, keyVaultUrl: cmk.keyVaultUrl },
                      kekIdentity:
                        cmk.userAssignedIdentity === undefined
                          ? { useSystemAssignedIdentity: true }
                          : { userAssignedIdentity: cmk.userAssignedIdentity },
                    },
                  },
            publicNetworkAccess: news.publicNetworkAccess,
            purviewConfiguration: purview,
            workspaceRepositoryConfiguration: repository,
            cspWorkspaceAdminProperties:
              news.initialWorkspaceAdminObjectId === undefined
                ? undefined
                : {
                    initialWorkspaceAdminObjectId:
                      news.initialWorkspaceAdminObjectId,
                  },
            azureADOnlyAuthentication: news.azureADOnlyAuthentication,
            trustedServiceBypassEnabled: news.trustedServiceBypassEnabled,
          },
        });
        passwordSent = true;
      }
      observed = yield* waitReady(subscriptionId, resourceGroup, name);

      // Sync mutable aspects against the observed workspace; PATCH only deltas.
      const props = observed.properties ?? {};
      const changed: synapse.WorkspacePatchPropertiesInput = {};
      if (
        news.publicNetworkAccess !== undefined &&
        lower(props.publicNetworkAccess) !== lower(news.publicNetworkAccess)
      ) {
        changed.publicNetworkAccess = news.publicNetworkAccess;
      }
      if (
        news.allowedAadTenantIdsForLinking !== undefined &&
        !fieldsMatch(
          props.managedVirtualNetworkSettings?.allowedAadTenantIdsForLinking ??
            [],
          news.allowedAadTenantIdsForLinking,
        )
      ) {
        changed.managedVirtualNetworkSettings = {
          ...props.managedVirtualNetworkSettings,
          allowedAadTenantIdsForLinking: news.allowedAadTenantIdsForLinking,
        };
      }
      if (
        purview !== undefined &&
        !fieldsMatch(props.purviewConfiguration, purview)
      ) {
        changed.purviewConfiguration = purview;
      }
      if (
        repository !== undefined &&
        !fieldsMatch(props.workspaceRepositoryConfiguration, repository)
      ) {
        changed.workspaceRepositoryConfiguration = repository;
      }
      if (
        !passwordSent &&
        news.sqlAdministratorLoginPassword !== undefined &&
        !sameSecret(fingerprint, output?.passwordFingerprint)
      ) {
        changed.sqlAdministratorLoginPassword =
          news.sqlAdministratorLoginPassword;
      }
      const identityChanged = identityDiffers(observed.identity, identity);
      const tagsChanged = tagsDiffer(observed.tags, tags);
      if (Object.keys(changed).length > 0 || identityChanged || tagsChanged) {
        yield* synapse.UpdateWorkspace({
          ...where,
          identity: identityChanged ? toIdentity(identity) : undefined,
          tags: tagsChanged ? tags : undefined,
          properties: Object.keys(changed).length > 0 ? changed : undefined,
        });
        // The PATCH is asynchronous; wait until the observed state converges.
        observed = yield* waitReady(
          subscriptionId,
          resourceGroup,
          name,
          (workspace) =>
            (!tagsChanged || !tagsDiffer(workspace.tags, tags)) &&
            (!identityChanged ||
              !identityDiffers(workspace.identity, identity)) &&
            (changed.publicNetworkAccess === undefined ||
              lower(workspace.properties?.publicNetworkAccess) ===
                lower(changed.publicNetworkAccess)),
        );
      }

      return toAttrs(resourceGroup, name, observed, fingerprint);
    }),

    delete: Effect.fn(function* ({ output }) {
      const { subscriptionId } = yield* AzureEnvironment.current;
      yield* ignoreNotFound(
        synapse.DeleteWorkspace({
          subscriptionId,
          resourceGroupName: output.resourceGroup,
          workspaceName: output.workspaceName,
        }),
      );
      yield* waitUntilGone(
        `synapse workspace ${output.workspaceName}`,
        getWorkspace(
          subscriptionId,
          output.resourceGroup,
          output.workspaceName,
        ),
        { interval: "10 seconds", times: 90 },
      );
    }),

    nuke: { dependsOn: ["Azure.Resources.ResourceGroup"] },
  });
