import * as apim from "@distilled.cloud/azure/apimanagement";
import * as Effect from "effect/Effect";
import * as Redacted from "effect/Redacted";
import { Unowned } from "../../AdoptPolicy.ts";
import { isResolved } from "../../Diff.ts";
import * as Provider from "../../Provider.ts";
import { Resource } from "../../Resource.ts";
import {
  ensureRegistered,
  ignoreNotFound,
  orUndefinedIfNotFound,
  waitUntilGone,
} from "../Arm.ts";
import { AzureEnvironment } from "../Environment.ts";
import type { Providers } from "../Providers.ts";
import { createEntityName, isParentOwned, sameName } from "./Common.ts";

export type SubscriptionState = apim.SubscriptionCreateParameterPropertiesState;

export interface SubscriptionProps {
  /** Resource group of the API Management service. Changing it replaces the subscription. */
  resourceGroup: string;
  /** API Management service that holds the subscription. Changing it replaces the subscription. */
  serviceName: string;
  /**
   * Subscription identifier (1-256 characters). If omitted, a unique name
   * is generated from the app, stage, and logical ID. Changing it replaces
   * the subscription.
   */
  name?: string;
  /**
   * What the key grants access to: a product or API ARM id (e.g.
   * `product.productId`), `/products/{productId}`, `/apis/{apiId}`, or
   * `/apis` for every API.
   */
  scope: string;
  /**
   * Display name.
   * @default the subscription identifier
   */
  displayName?: string;
  /**
   * Subscription state.
   * @default "active"
   */
  state?: SubscriptionState;
  /** Allow request tracing with this key. */
  allowTracing?: boolean;
  /** Primary key. Generated by API Management if omitted. */
  primaryKey?: Redacted.Redacted<string>;
  /** Secondary key. Generated by API Management if omitted. */
  secondaryKey?: Redacted.Redacted<string>;
}

export interface Subscription extends Resource<
  "Azure.ApiManagement.Subscription",
  SubscriptionProps,
  {
    /** Subscription identifier. */
    subscriptionName: string;
    /** ARM resource ID of the subscription. */
    subscriptionResourceId: string;
    /** API Management service that holds the subscription. */
    serviceName: string;
    /** Resource group of the service. */
    resourceGroup: string;
    /** Scope the key grants access to, as reported by Azure. */
    scope: string;
    /** Display name. */
    displayName: string | undefined;
    /** Subscription state. */
    state: string;
    /** Primary subscription key (`Ocp-Apim-Subscription-Key`). */
    primaryKey: Redacted.Redacted<string> | undefined;
    /** Secondary subscription key. */
    secondaryKey: Redacted.Redacted<string> | undefined;
  },
  never,
  Providers
> {}

/**
 * An API Management subscription — a pair of keys granting access to a
 * product, an API, or all APIs. (Not an Azure subscription.)
 *
 * @see https://learn.microsoft.com/azure/api-management/api-management-subscriptions
 *
 * ### Creating a Subscription
 * **Example:** Key for a product
 * ```typescript
 * const sub = yield* Azure.ApiManagement.Subscription("client", {
 *   resourceGroup: group.resourceGroupName,
 *   serviceName: apim.serviceName,
 *   scope: product.productId,
 * });
 * // send sub.primaryKey as the Ocp-Apim-Subscription-Key header
 * ```
 *
 * **Example:** All-APIs key with tracing enabled
 * ```typescript
 * const admin = yield* Azure.ApiManagement.Subscription("admin", {
 *   resourceGroup: group.resourceGroupName,
 *   serviceName: apim.serviceName,
 *   scope: "/apis",
 *   allowTracing: true,
 * });
 * ```
 *
 * @resource
 */
export const Subscription = Resource<Subscription>(
  "Azure.ApiManagement.Subscription",
);

/** `/products/x`, `/apis/x`, or `/apis` from a scope path or ARM id. */
const normalizeScope = (scope: string) => {
  const lower = scope.toLowerCase();
  const index = Math.max(
    lower.lastIndexOf("/products/"),
    lower.lastIndexOf("/apis"),
  );
  return index >= 0 ? scope.slice(index) : scope;
};

const getSubscription = (
  subscriptionId: string,
  resourceGroupName: string,
  serviceName: string,
  sid: string,
) =>
  orUndefinedIfNotFound(
    apim.GetSubscription({
      subscriptionId,
      resourceGroupName,
      serviceName,
      sid,
    }),
  );

const toAttrs = (
  resourceGroup: string,
  serviceName: string,
  name: string,
  subscription: apim.GetSubscriptionResponse,
  secrets: apim.ListSubscriptionSecretsResponse | undefined,
): Subscription["Attributes"] => ({
  subscriptionName: name,
  subscriptionResourceId: subscription.id ?? "",
  serviceName,
  resourceGroup,
  scope: subscription.properties?.scope ?? "",
  displayName: subscription.properties?.displayName,
  state: subscription.properties?.state ?? "active",
  primaryKey: secrets?.primaryKey
    ? Redacted.make(secrets.primaryKey)
    : undefined,
  secondaryKey: secrets?.secondaryKey
    ? Redacted.make(secrets.secondaryKey)
    : undefined,
});

export const SubscriptionProvider = () =>
  Provider.succeed(Subscription, {
    stables: [
      "subscriptionName",
      "subscriptionResourceId",
      "serviceName",
      "resourceGroup",
    ],

    // Subscriptions live inside a service; nuke removes them with it.
    list: Effect.fn(function* () {
      return [];
    }),

    diff: Effect.fn(function* ({ news, output }) {
      if (!isResolved(news) || output === undefined) return undefined;
      if (
        !sameName(news.resourceGroup, output.resourceGroup) ||
        !sameName(news.serviceName, output.serviceName) ||
        (news.name !== undefined &&
          !sameName(news.name, output.subscriptionName))
      ) {
        return { action: "replace" } as const;
      }
      return undefined;
    }),

    read: Effect.fn(function* ({ id, olds, output }) {
      const { subscriptionId } = yield* AzureEnvironment.current;
      const resourceGroup = output?.resourceGroup ?? olds?.resourceGroup;
      const serviceName = output?.serviceName ?? olds?.serviceName;
      if (resourceGroup === undefined || serviceName === undefined) {
        return undefined;
      }
      const name =
        output?.subscriptionName ?? olds?.name ?? (yield* createEntityName(id));
      const where = {
        subscriptionId,
        resourceGroupName: resourceGroup,
        serviceName,
        sid: name,
      };
      const observed = yield* getSubscription(
        subscriptionId,
        resourceGroup,
        serviceName,
        name,
      );
      if (observed === undefined) return undefined;
      const secrets = yield* orUndefinedIfNotFound(
        apim.ListSubscriptionSecrets(where),
      );
      const attrs = toAttrs(
        resourceGroup,
        serviceName,
        name,
        observed,
        secrets,
      );
      return (yield* isParentOwned(subscriptionId, resourceGroup, serviceName))
        ? attrs
        : Unowned(attrs);
    }),

    reconcile: Effect.fn(function* ({ id, news, output }) {
      const { subscriptionId } = yield* AzureEnvironment.current;
      yield* ensureRegistered(subscriptionId, "Microsoft.ApiManagement");
      const { resourceGroup, serviceName } = news;
      const name =
        news.name ?? output?.subscriptionName ?? (yield* createEntityName(id));
      const where = {
        subscriptionId,
        resourceGroupName: resourceGroup,
        serviceName,
        sid: name,
      };
      const desired = {
        scope: normalizeScope(news.scope),
        displayName: news.displayName ?? name,
        state: news.state ?? "active",
        allowTracing: news.allowTracing,
        primaryKey: news.primaryKey
          ? Redacted.value(news.primaryKey)
          : undefined,
        secondaryKey: news.secondaryKey
          ? Redacted.value(news.secondaryKey)
          : undefined,
      };

      // Observe: GET omits the keys, so read them via listSecrets.
      const observed = yield* getSubscription(
        subscriptionId,
        resourceGroup,
        serviceName,
        name,
      );
      let inSync = false;
      if (observed?.properties !== undefined) {
        const props = observed.properties;
        const secrets =
          desired.primaryKey !== undefined || desired.secondaryKey !== undefined
            ? yield* apim.ListSubscriptionSecrets(where)
            : undefined;
        inSync =
          sameName(normalizeScope(props.scope), desired.scope) &&
          props.displayName === desired.displayName &&
          props.state === desired.state &&
          (desired.allowTracing === undefined ||
            (props.allowTracing ?? false) === desired.allowTracing) &&
          (desired.primaryKey === undefined ||
            secrets?.primaryKey === desired.primaryKey) &&
          (desired.secondaryKey === undefined ||
            secrets?.secondaryKey === desired.secondaryKey);
      }

      // Ensure + sync with one upsert; never email the owner.
      if (!inSync) {
        yield* apim.SubscriptionCreateOrUpdate({
          ...where,
          notify: false,
          properties: desired,
        });
      }
      const current = yield* apim.GetSubscription(where);
      const secrets = yield* apim.ListSubscriptionSecrets(where);
      return toAttrs(resourceGroup, serviceName, name, current, secrets);
    }),

    delete: Effect.fn(function* ({ output }) {
      const { subscriptionId } = yield* AzureEnvironment.current;
      yield* ignoreNotFound(
        apim.DeleteSubscription({
          subscriptionId,
          resourceGroupName: output.resourceGroup,
          serviceName: output.serviceName,
          sid: output.subscriptionName,
        }),
      );
      yield* waitUntilGone(
        `API Management subscription ${output.subscriptionName}`,
        getSubscription(
          subscriptionId,
          output.resourceGroup,
          output.serviceName,
          output.subscriptionName,
        ),
        { interval: "2 seconds", times: 15 },
      );
    }),
  });
