import * as cdn from "@distilled.cloud/azure/cdn";
import * as Effect from "effect/Effect";
import { Unowned } from "../../AdoptPolicy.ts";
import { isResolved } from "../../Diff.ts";
import * as Provider from "../../Provider.ts";
import { Resource } from "../../Resource.ts";
import {
  desiredTags,
  ensureRegistered,
  ignoreNotFound,
  isOwned,
  orUndefinedIfNotFound,
  tagsDiffer,
  userTags,
  waitUntilGone,
} from "../Arm.ts";
import { AzureEnvironment } from "../Environment.ts";
import type { Providers } from "../Providers.ts";
import {
  AFD_DELETE_BUDGET,
  changedFields,
  createAfdName,
  sameName,
  waitForAfd,
  whileProfileBusy,
} from "./CdnCommon.ts";

/** Scope in which the endpoint's generated host-name label can be reused. */
export type AutoGeneratedDomainNameLabelScope =
  | "TenantReuse"
  | "SubscriptionReuse"
  | "ResourceGroupReuse"
  | "NoReuse";

export interface AfdEndpointProps {
  /** Resource group of the profile. Changing it replaces the endpoint. */
  resourceGroup: string;
  /** Front Door profile that holds the endpoint. Changing it replaces the endpoint. */
  profile: string;
  /**
   * Endpoint name: 2-46 letters, digits, and hyphens. Front Door appends a
   * hash and serves it at `<name>-<hash>.<zone>.azurefd.net`. If omitted, a
   * unique name is generated from the app, stage, and logical ID. Changing
   * it replaces the endpoint.
   */
  name?: string;
  /**
   * Whether the endpoint serves traffic.
   * @default "Enabled"
   */
  enabledState?: "Enabled" | "Disabled";
  /**
   * When `Enabled`, only custom domains with mutual TLS can be added to the
   * endpoint's routes.
   * @default "Disabled"
   */
  enforceMtls?: "Enabled" | "Disabled";
  /**
   * Scope in which the generated host-name hash can be reused after the
   * endpoint is deleted. Changing it replaces the endpoint.
   * @default "TenantReuse"
   */
  autoGeneratedDomainNameLabelScope?: AutoGeneratedDomainNameLabelScope;
  /**
   * User tags. Alchemy ownership tags (`alchemy::stack`, `alchemy::stage`,
   * `alchemy::id`) are merged in automatically.
   */
  tags?: Record<string, string>;
}

export interface AfdEndpoint extends Resource<
  "Azure.Cdn.AfdEndpoint",
  AfdEndpointProps,
  {
    /** Name of the endpoint. */
    endpointName: string;
    /** ARM resource ID of the endpoint; use it in security policy associations. */
    endpointId: string;
    /** Front Door profile that holds the endpoint. */
    profile: string;
    /** Resource group of the profile. */
    resourceGroup: string;
    /** Public host name, e.g. `app-abc123.z01.azurefd.net`. */
    hostName: string;
    /** Whether the endpoint serves traffic. */
    enabledState: string | undefined;
    /** Host-name label reuse scope. */
    autoGeneratedDomainNameLabelScope: string | undefined;
    /** Edge deployment status (`NotStarted`, `InProgress`, `Succeeded`, `Failed`). */
    deploymentStatus: string | undefined;
    /** User tags (Alchemy ownership tags stripped). */
    tags: Record<string, string>;
  },
  never,
  Providers
> {}

/**
 * An Azure Front Door endpoint — the `*.azurefd.net` host name clients
 * connect to. Attach routes to send its traffic to origin groups.
 *
 * @see https://learn.microsoft.com/azure/frontdoor/endpoint
 *
 * ### Creating an Endpoint
 * **Example:** Endpoint on a Front Door profile
 * ```typescript
 * const profile = yield* Azure.Cdn.Profile("cdn", {
 *   resourceGroup: group.resourceGroupName,
 * });
 * const endpoint = yield* Azure.Cdn.AfdEndpoint("web", {
 *   resourceGroup: group.resourceGroupName,
 *   profile: profile.profileName,
 * });
 * // endpoint.hostName → "web-...-abc123.z01.azurefd.net"
 * ```
 *
 * **Example:** Disabled endpoint
 * ```typescript
 * const endpoint = yield* Azure.Cdn.AfdEndpoint("web", {
 *   resourceGroup: group.resourceGroupName,
 *   profile: profile.profileName,
 *   enabledState: "Disabled",
 * });
 * ```
 *
 * @resource
 */
export const AfdEndpoint = Resource<AfdEndpoint>("Azure.Cdn.AfdEndpoint");

const createEndpointName = (id: string) => createAfdName(id, 46);

const getEndpoint = (
  subscriptionId: string,
  resourceGroupName: string,
  profileName: string,
  endpointName: string,
) =>
  orUndefinedIfNotFound(
    cdn.GetAFDEndpoint({
      subscriptionId,
      resourceGroupName,
      profileName,
      endpointName,
    }),
  );

const toAttrs = (
  resourceGroup: string,
  profile: string,
  name: string,
  endpoint: cdn.GetAFDEndpointResponse,
): AfdEndpoint["Attributes"] => ({
  endpointName: name,
  endpointId: endpoint.id ?? "",
  profile,
  resourceGroup,
  hostName: endpoint.properties?.hostName ?? "",
  enabledState: endpoint.properties?.enabledState,
  autoGeneratedDomainNameLabelScope:
    endpoint.properties?.autoGeneratedDomainNameLabelScope,
  deploymentStatus: endpoint.properties?.deploymentStatus,
  tags: userTags(endpoint.tags),
});

export const AfdEndpointProvider = () =>
  Provider.succeed(AfdEndpoint, {
    stables: [
      "endpointName",
      "endpointId",
      "profile",
      "resourceGroup",
      "hostName",
    ],

    // Endpoints are deleted with their profile.
    list: Effect.fn(function* () {
      return [];
    }),

    diff: Effect.fn(function* ({ news, output }) {
      if (!isResolved(news) || output === undefined) return undefined;
      if (
        !sameName(news.resourceGroup, output.resourceGroup) ||
        !sameName(news.profile, output.profile) ||
        (news.name !== undefined &&
          !sameName(news.name, output.endpointName)) ||
        (news.autoGeneratedDomainNameLabelScope ?? "TenantReuse") !==
          (output.autoGeneratedDomainNameLabelScope ?? "TenantReuse")
      ) {
        return { action: "replace" } as const;
      }
      return undefined;
    }),

    read: Effect.fn(function* ({ id, olds, output }) {
      const { subscriptionId } = yield* AzureEnvironment.current;
      const resourceGroup = output?.resourceGroup ?? olds?.resourceGroup;
      const profile = output?.profile ?? olds?.profile;
      if (resourceGroup === undefined || profile === undefined)
        return undefined;
      const name =
        output?.endpointName ?? olds?.name ?? (yield* createEndpointName(id));
      const observed = yield* getEndpoint(
        subscriptionId,
        resourceGroup,
        profile,
        name,
      );
      if (observed === undefined) return undefined;
      const attrs = toAttrs(resourceGroup, profile, name, observed);
      return (yield* isOwned(id, observed.tags)) ? attrs : Unowned(attrs);
    }),

    reconcile: Effect.fn(function* ({ id, news, output }) {
      const { subscriptionId } = yield* AzureEnvironment.current;
      yield* ensureRegistered(subscriptionId, "Microsoft.Cdn");
      const { resourceGroup, profile } = news;
      const name =
        news.name ?? output?.endpointName ?? (yield* createEndpointName(id));
      const tags = yield* desiredTags(id, news.tags);
      const properties = {
        enabledState: news.enabledState ?? "Enabled",
        enforceMtls: news.enforceMtls,
      };
      const where = {
        subscriptionId,
        resourceGroupName: resourceGroup,
        profileName: profile,
        endpointName: name,
      };
      const get = getEndpoint(subscriptionId, resourceGroup, profile, name);
      const label = `Front Door endpoint ${name}`;

      // Observe.
      let observed = yield* get;

      // Ensure.
      if (observed === undefined) {
        yield* cdn
          .CreateAFDEndpoint({
            ...where,
            location: "global",
            tags,
            properties: {
              ...properties,
              autoGeneratedDomainNameLabelScope:
                news.autoGeneratedDomainNameLabelScope,
            },
          })
          .pipe(Effect.retry(whileProfileBusy));
      }
      observed = yield* waitForAfd(
        label,
        get,
        (e) => e.properties?.provisioningState,
      );

      // Sync tags and mutable properties against observed state.
      const changed = changedFields(properties, observed.properties);
      const tagsChanged = tagsDiffer(observed.tags, tags);
      if (Object.keys(changed).length > 0 || tagsChanged) {
        yield* cdn
          .UpdateAFDEndpoint({
            ...where,
            tags: tagsChanged ? tags : undefined,
            properties: Object.keys(changed).length > 0 ? changed : undefined,
          })
          .pipe(Effect.retry(whileProfileBusy));
        observed = yield* waitForAfd(
          label,
          get,
          (e) => e.properties?.provisioningState,
        );
      }

      return toAttrs(resourceGroup, profile, name, observed);
    }),

    delete: Effect.fn(function* ({ output }) {
      const { subscriptionId } = yield* AzureEnvironment.current;
      yield* ignoreNotFound(
        cdn
          .DeleteAFDEndpoint({
            subscriptionId,
            resourceGroupName: output.resourceGroup,
            profileName: output.profile,
            endpointName: output.endpointName,
          })
          .pipe(Effect.retry(whileProfileBusy)),
      );
      yield* waitUntilGone(
        `Front Door endpoint ${output.endpointName}`,
        getEndpoint(
          subscriptionId,
          output.resourceGroup,
          output.profile,
          output.endpointName,
        ),
        AFD_DELETE_BUDGET,
      );
    }),
  });
