import type * as aci from "@distilled.cloud/azure/containerinstance";
import type * as Redacted from "effect/Redacted";
import { createContainerAppsName, reveal } from "../ContainerApps/common.ts";

export {
  fingerprint,
  lower,
  matchesDesired,
  reveal,
  sameLocation,
} from "../ContainerApps/common.ts";

/**
 * Deterministic Container Instances name (container groups, profiles,
 * NGroups, sandbox groups): lowercase letters, digits, and single hyphens,
 * starting with a letter, at most 63 characters.
 */
export const createContainerInstanceName = (id: string) =>
  createContainerAppsName(id, 63);

/** Spec fields shared by container groups and container group profiles. */
type ComparableSpec = {
  readonly containers: ReadonlyArray<aci.ContainerInput>;
  readonly osType?: string;
  readonly sku?: string;
  readonly priority?: string;
  readonly restartPolicy?: string;
  readonly ipAddress?: aci.IpAddressInput;
  readonly imageRegistryCredentials?: ReadonlyArray<aci.ImageRegistryCredential>;
  readonly diagnostics?: aci.ContainerGroupDiagnostics;
};

/** A container of a container group or container group profile. */
export interface ContainerInstanceContainer {
  /** Container name, unique within the group. */
  name: string;
  /** Image to run, e.g. `mcr.microsoft.com/azuredocs/aci-helloworld`. */
  image: string;
  /**
   * Requested CPU cores (e.g. `0.5`, `1`). Changing it replaces a
   * container group.
   * @default 1
   */
  cpu?: number;
  /**
   * Requested memory in GB (e.g. `0.5`, `1.5`). Changing it replaces a
   * container group.
   * @default 1.5
   */
  memoryInGB?: number;
  /** Requested GPUs. GPU SKUs are not available on every subscription. */
  gpu?: aci.GpuResource;
  /** Resource limits (upper bounds above the requests). */
  limits?: aci.ResourceLimits;
  /** Command (entrypoint override) in exec form. */
  command?: string[];
  /** Ports the container exposes. */
  ports?: aci.ContainerPort[];
  /** Plain environment variables. */
  environment?: Record<string, string>;
  /**
   * Secure environment variables. Azure never returns their values, so a
   * changed value is detected against the previous deploy's props.
   */
  secureEnvironment?: Record<string, string | Redacted.Redacted<string>>;
  /** Volume mounts, referencing the group's `volumes` by name. */
  volumeMounts?: aci.VolumeMount[];
  /** Liveness probe. */
  livenessProbe?: aci.ContainerProbe;
  /** Readiness probe. */
  readinessProbe?: aci.ContainerProbe;
  /** Container security context. */
  securityContext?: aci.SecurityContextDefinition;
}

/** Public or private IP address of a container group. */
export interface ContainerInstanceIpAddress {
  /**
   * `Public` for an internet-facing IP, `Private` for a VNet IP (requires
   * `subnetIds`). Changing it replaces a container group.
   */
  type: "Public" | "Private";
  /** Ports opened on the IP; each must also be exposed by a container. */
  ports: aci.Port[];
  /**
   * DNS label, giving the FQDN `{label}.{region}.azurecontainer.io`.
   * Changing it replaces a container group.
   */
  dnsNameLabel?: string;
  /**
   * Reuse scope of the DNS label (adds a hash to the label to prevent
   * subdomain takeover). Changing it replaces a container group.
   */
  autoGeneratedDomainNameLabelScope?: aci.IpAddressInputAutoGeneratedDomainNameLabelScope;
}

/** Managed identity of a container group or NGroup. */
export interface ContainerInstanceIdentity {
  /** Identity type. */
  type:
    | "SystemAssigned"
    | "UserAssigned"
    | "SystemAssigned, UserAssigned"
    | "None";
  /** ARM IDs of the user-assigned identities to attach. */
  userAssignedIdentities?: string[];
}

/** The wire shape of a managed identity. */
export const toIdentity = (identity: ContainerInstanceIdentity | undefined) =>
  identity === undefined
    ? undefined
    : {
        type: identity.type,
        userAssignedIdentities:
          identity.userAssignedIdentities !== undefined &&
          identity.userAssignedIdentities.length > 0
            ? Object.fromEntries(
                identity.userAssignedIdentities.map((id) => [id, {}]),
              )
            : undefined,
      };

const normalizeIdentityType = (type: string | undefined) =>
  (type ?? "None").toLowerCase().replaceAll(" ", "");

/** Whether the observed identity matches the desired one. */
export const identityMatches = (
  desired:
    | {
        readonly type: string;
        readonly userAssignedIdentities?: ReadonlyArray<string>;
      }
    | undefined,
  observed:
    | {
        readonly type?: string;
        readonly userAssignedIdentities?: object;
      }
    | undefined,
) => {
  if (desired === undefined) return true;
  if (
    normalizeIdentityType(desired.type) !==
    normalizeIdentityType(observed?.type)
  ) {
    return false;
  }
  const want = (desired.userAssignedIdentities ?? [])
    .map((id) => id.toLowerCase())
    .sort();
  const have = Object.keys(observed?.userAssignedIdentities ?? {})
    .map((id) => id.toLowerCase())
    .sort();
  return want.join("|") === have.join("|");
};

/** Placeholder for a secure env value, which Azure never echoes back. */
const SECURE = "<secure>";

/** The wire shape of containers (secure values revealed). */
export const toContainers = (
  containers: ReadonlyArray<ContainerInstanceContainer>,
): aci.ContainerInput[] =>
  containers.map((c) => ({
    name: c.name,
    properties: {
      image: c.image,
      command: c.command,
      ports: c.ports,
      environmentVariables: [
        ...Object.entries(c.environment ?? {}).map(([name, value]) => ({
          name,
          value,
        })),
        ...Object.entries(c.secureEnvironment ?? {}).map(([name, value]) => ({
          name,
          secureValue: reveal(value),
        })),
      ],
      resources: {
        requests: {
          cpu: c.cpu ?? 1,
          memoryInGB: c.memoryInGB ?? 1.5,
          gpu: c.gpu,
        },
        limits: c.limits,
      },
      volumeMounts: c.volumeMounts,
      livenessProbe: c.livenessProbe,
      readinessProbe: c.readinessProbe,
      securityContext: c.securityContext,
    },
  }));

/**
 * Comparable view of containers: environment variables as a name → value
 * map (order-insensitive, secure values masked) and the remaining
 * properties as sent. Used for both desired and observed containers.
 */
export const comparableContainers = <
  P extends {
    readonly environmentVariables?: ReadonlyArray<aci.EnvironmentVariable>;
  },
>(
  containers: ReadonlyArray<{ readonly name: string; readonly properties: P }>,
) =>
  [...containers]
    .sort((a, b) => a.name.localeCompare(b.name))
    .map(({ name, properties }) => {
      const { environmentVariables, ...rest } = properties;
      return {
        name,
        environment: Object.fromEntries(
          (environmentVariables ?? []).map((v) => [
            v.name,
            v.value !== undefined ? v.value : SECURE,
          ]),
        ),
        properties: rest,
      };
    });

/** Container names, sorted; a changed set replaces a container group. */
export const containerNames = (
  containers: ReadonlyArray<{ readonly name: string }>,
) =>
  containers
    .map((c) => c.name)
    .sort()
    .join("|");

/** Requested resources per container; changing them replaces a group. */
export const containerResources = (
  containers: ReadonlyArray<ContainerInstanceContainer>,
) =>
  [...containers]
    .sort((a, b) => a.name.localeCompare(b.name))
    .map((c) => `${c.name}:${c.cpu ?? 1}:${c.memoryInGB ?? 1.5}`)
    .join("|");

/** Credentials for pulling images from a private registry. */
export interface ContainerInstanceRegistryCredential {
  /** Registry login server, e.g. `myregistry.azurecr.io`. */
  server: string;
  /** Registry username. */
  username?: string;
  /** Registry password. */
  password?: string | Redacted.Redacted<string>;
  /** ARM ID of a user-assigned identity used to pull instead of a password. */
  identity?: string;
}

/** A Log Analytics workspace that receives the group's logs. */
export interface ContainerInstanceLogAnalytics {
  /** Workspace (customer) ID. */
  workspaceId: string;
  /** Workspace primary or secondary key. */
  workspaceKey: string | Redacted.Redacted<string>;
  /** Log type to send. @default "ContainerInsights" */
  logType?: aci.LogAnalyticsLogType;
}

/** The wire shape of registry credentials (passwords revealed). */
export const toRegistryCredentials = (
  credentials: ReadonlyArray<ContainerInstanceRegistryCredential> | undefined,
): aci.ImageRegistryCredential[] | undefined =>
  credentials?.map((c) => ({
    server: c.server,
    username: c.username,
    password: reveal(c.password),
    identity: c.identity,
  }));

/** The wire shape of Log Analytics diagnostics (key revealed). */
export const toDiagnostics = (
  logAnalytics: ContainerInstanceLogAnalytics | undefined,
): aci.ContainerGroupDiagnostics | undefined =>
  logAnalytics === undefined
    ? undefined
    : {
        logAnalytics: {
          workspaceId: logAnalytics.workspaceId,
          workspaceKey: reveal(logAnalytics.workspaceKey) ?? "",
          logType: logAnalytics.logType,
        },
      };

/**
 * The observable subset of the desired state. Azure never echoes secrets
 * (secure env values, registry passwords, volume keys, workspace keys);
 * those changes are detected against the previous props instead.
 */
export const comparable = (properties: ComparableSpec) => ({
  containers: comparableContainers(properties.containers),
  osType: properties.osType,
  sku: properties.sku,
  priority: properties.priority,
  restartPolicy: properties.restartPolicy,
  ipAddress:
    properties.ipAddress === undefined
      ? undefined
      : {
          type: properties.ipAddress.type,
          ports: properties.ipAddress.ports,
          dnsNameLabel: properties.ipAddress.dnsNameLabel,
        },
  imageRegistryCredentials: properties.imageRegistryCredentials?.map((c) => ({
    server: c.server,
    username: c.username,
    identity: c.identity,
  })),
  diagnostics:
    properties.diagnostics?.logAnalytics === undefined
      ? undefined
      : {
          workspaceId: properties.diagnostics.logAnalytics.workspaceId,
          logType: properties.diagnostics.logAnalytics.logType,
        },
});
