export * as ApiManagement from "./ApiManagement/index.ts";
export * as AppConfiguration from "./AppConfiguration/index.ts";
export * from "./AuthProvider.ts";
export * as Authorization from "./Authorization/index.ts";
export * as Automation from "./Automation/index.ts";
export * as AzureStackHCI from "./AzureStackHCI/index.ts";
export * as CognitiveServices from "./CognitiveServices/index.ts";
export * as Compute from "./Compute/index.ts";
export * as ContainerApps from "./ContainerApps/index.ts";
export * as ContainerInstance from "./ContainerInstance/index.ts";
export * as ContainerRegistry from "./ContainerRegistry/index.ts";
export * as ContainerService from "./ContainerService/index.ts";
export * as CosmosDB from "./CosmosDB/index.ts";
export * as DataFactory from "./DataFactory/index.ts";
export * as DevTestLabs from "./DevTestLabs/index.ts";
export * as DnsResolver from "./DnsResolver/index.ts";
export * from "./Credentials.ts";
export * from "./Environment.ts";
export * as Edge from "./Edge/index.ts";
export * as EventGrid from "./EventGrid/index.ts";
export * as EventHub from "./EventHub/index.ts";
export * as LogAnalytics from "./LogAnalytics/index.ts";
export * as KeyVault from "./KeyVault/index.ts";
export * as Logic from "./Logic/index.ts";
export * as MachineLearning from "./MachineLearning/index.ts";
export * as ManagedIdentity from "./ManagedIdentity/index.ts";
export * as ManagedNetworkFabric from "./ManagedNetworkFabric/index.ts";
export * as Monitor from "./Monitor/index.ts";
export * as MySQL from "./MySQL/index.ts";
export * as Network from "./Network/index.ts";
export * from "./Providers.ts";
export * as Policy from "./Policy/index.ts";
export * as PostgreSQL from "./PostgreSQL/index.ts";
export * as PrivateDns from "./PrivateDns/index.ts";
export * as RecoveryServices from "./RecoveryServices/index.ts";
export * as Redis from "./Redis/index.ts";
export * as Resources from "./Resources/index.ts";
export * as Search from "./Search/index.ts";
export * as SecurityInsights from "./SecurityInsights/index.ts";
export * as ServiceBus from "./ServiceBus/index.ts";
export * as Sql from "./Sql/index.ts";
export * as Storage from "./Storage/index.ts";
export * as Synapse from "./Synapse/index.ts";
export * as VMware from "./VMware/index.ts";
export * as Web from "./Web/index.ts";
