import * as network from "@distilled.cloud/azure/network";
import * as Effect from "effect/Effect";
import { Unowned } from "../../AdoptPolicy.ts";
import { isResolved } from "../../Diff.ts";
import * as Provider from "../../Provider.ts";
import { Resource } from "../../Resource.ts";
import {
  desiredTags,
  ensureRegistered,
  hasAnyAlchemyTag,
  ignoreNotFound,
  isOwned,
  orUndefinedIfNotFound,
  requireSinglePage,
  resourceGroupOf,
  tagsDiffer,
  userTags,
} from "../Arm.ts";
import { AzureEnvironment } from "../Environment.ts";
import type { Providers } from "../Providers.ts";
import {
  canonical,
  createNetworkName,
  lower,
  sameId,
  sameSet,
  waitNetworkGone,
  waitNetworkProvisioned,
  whileNetworkBusy,
} from "./common.ts";

export interface PrivateLinkServiceConnectionSpec {
  /**
   * Name of the connection.
   * @default the private endpoint name
   */
  name?: string;
  /**
   * ARM ID of the target resource (e.g. a storage account or Key Vault) or
   * private link service.
   */
  privateLinkServiceId: string;
  /**
   * Target sub-resources, e.g. `["blob"]` for a storage account or
   * `["vault"]` for Key Vault. Omit for a private link service.
   */
  groupIds?: string[];
  /** Message sent to the owner of the target with a manual request. */
  requestMessage?: string;
}

export interface PrivateEndpointStaticIpConfiguration {
  /** Name of the IP configuration. */
  name: string;
  /** Target sub-resource, e.g. `blob`. */
  groupId: string;
  /** Member name of the sub-resource, e.g. `blob`. */
  memberName: string;
  /** Static private IP inside the subnet. */
  privateIpAddress: string;
}

export interface PrivateEndpointProps {
  /**
   * Resource group the private endpoint is created in. Changing it
   * replaces the private endpoint.
   */
  resourceGroup: string;
  /**
   * Name of the private endpoint: 2-64 letters, digits, `_`, `.`, and `-`.
   * If omitted, a unique name is generated from the app, stage, and
   * logical ID. Changing it replaces the private endpoint.
   */
  name?: string;
  /**
   * Azure location; must match the subnet's virtual network. Changing it
   * replaces the private endpoint.
   * @default the `Azure.Location` layer, else the profile location, else `eastus`
   */
  location?: string;
  /**
   * ARM ID of the subnet the endpoint's NIC is placed in. Changing it
   * replaces the private endpoint.
   */
  subnetId: string;
  /**
   * Auto-approved connections (targets you own or have access to).
   * Changing a target or its group IDs replaces the private endpoint.
   */
  privateLinkServiceConnections?: PrivateLinkServiceConnectionSpec[];
  /**
   * Connections that the target's owner must approve (e.g. cross-tenant).
   * Changing them replaces the private endpoint.
   */
  manualPrivateLinkServiceConnections?: PrivateLinkServiceConnectionSpec[];
  /**
   * Name of the endpoint's network interface. Changing it replaces the
   * private endpoint.
   * @default generated by Azure
   */
  customNetworkInterfaceName?: string;
  /**
   * Static IPs for the endpoint. Changing them replaces the private
   * endpoint.
   * @default dynamically allocated
   */
  ipConfigurations?: PrivateEndpointStaticIpConfiguration[];
  /** ARM IDs of application security groups the endpoint joins. */
  applicationSecurityGroupIds?: string[];
  /**
   * User tags. Alchemy ownership tags (`alchemy::stack`, `alchemy::stage`,
   * `alchemy::id`) are merged in automatically.
   */
  tags?: Record<string, string>;
}

export interface PrivateEndpointDnsConfig {
  /** FQDN of the target that resolves to the endpoint. */
  fqdn: string | undefined;
  /** Private IPs of the endpoint for that FQDN. */
  ipAddresses: string[];
}

export interface PrivateEndpoint extends Resource<
  "Azure.Network.PrivateEndpoint",
  PrivateEndpointProps,
  {
    /** Name of the private endpoint. */
    privateEndpointName: string;
    /** ARM resource ID of the private endpoint. */
    privateEndpointId: string;
    /** Resource group that holds the private endpoint. */
    resourceGroup: string;
    /** Location of the private endpoint. */
    location: string;
    /** Subnet the endpoint lives in. */
    subnetId: string;
    /** IDs of the network interfaces Azure created for the endpoint. */
    networkInterfaceIds: string[];
    /** FQDN-to-private-IP mappings (for custom DNS). */
    customDnsConfigs: PrivateEndpointDnsConfig[];
    /**
     * Status of the first connection: `Approved`, `Pending`, `Rejected`,
     * or `Disconnected`.
     */
    connectionStatus: string | undefined;
    /** User tags (Alchemy ownership tags stripped). */
    tags: Record<string, string>;
  },
  never,
  Providers
> {}

/**
 * An Azure private endpoint — a NIC with a private IP in your subnet that
 * connects privately to a PaaS resource (Storage, Key Vault, SQL, ...) or
 * a private link service over Azure Private Link.
 *
 * Pair it with a `privatelink.*` Private DNS zone so the target's FQDN
 * resolves to the private IP; until then `customDnsConfigs` lists the
 * mappings.
 *
 * @see https://learn.microsoft.com/azure/private-link/private-endpoint-overview
 *
 * ### Connecting to a Storage Account
 * **Example:** Private endpoint for blob storage
 * ```typescript
 * const account = yield* Azure.Storage.StorageAccount("files", {
 *   resourceGroup: group.resourceGroupName,
 *   publicNetworkAccess: "Disabled",
 * });
 * const endpoint = yield* Azure.Network.PrivateEndpoint("files-blob", {
 *   resourceGroup: group.resourceGroupName,
 *   subnetId: subnet.subnetId,
 *   privateLinkServiceConnections: [
 *     { privateLinkServiceId: account.storageAccountId, groupIds: ["blob"] },
 *   ],
 * });
 * ```
 *
 * ### Manual Approval
 * **Example:** Connection the target owner approves
 * ```typescript
 * const endpoint = yield* Azure.Network.PrivateEndpoint("partner", {
 *   resourceGroup: group.resourceGroupName,
 *   subnetId: subnet.subnetId,
 *   manualPrivateLinkServiceConnections: [
 *     {
 *       privateLinkServiceId: partnerServiceId,
 *       requestMessage: "Please approve",
 *     },
 *   ],
 * });
 * ```
 *
 * @resource
 */
export const PrivateEndpoint = Resource<PrivateEndpoint>(
  "Azure.Network.PrivateEndpoint",
);

type Observed = network.GetPrivateEndpointResponse;

const getEndpoint = (
  subscriptionId: string,
  resourceGroupName: string,
  privateEndpointName: string,
) =>
  orUndefinedIfNotFound(
    network.GetPrivateEndpoint({
      subscriptionId,
      resourceGroupName,
      privateEndpointName,
    }),
  );

const toAttrs = (
  resourceGroup: string,
  name: string,
  endpoint: Observed,
): PrivateEndpoint["Attributes"] => {
  const p = endpoint.properties;
  const connection =
    p?.privateLinkServiceConnections?.[0] ??
    p?.manualPrivateLinkServiceConnections?.[0];
  return {
    privateEndpointName: name,
    privateEndpointId: endpoint.id ?? "",
    resourceGroup,
    location: endpoint.location ?? "",
    subnetId: p?.subnet?.id ?? "",
    networkInterfaceIds: (p?.networkInterfaces ?? []).flatMap((nic) =>
      nic.id === undefined ? [] : [nic.id],
    ),
    customDnsConfigs: (p?.customDnsConfigs ?? []).map((config) => ({
      fqdn: config.fqdn,
      ipAddresses: [...(config.ipAddresses ?? [])],
    })),
    connectionStatus:
      connection?.properties?.privateLinkServiceConnectionState?.status,
    tags: userTags(endpoint.tags),
  };
};

/** Comparable identity of connections (target + group IDs). */
const connectionKey = (
  connections: ReadonlyArray<PrivateLinkServiceConnectionSpec> | undefined,
) =>
  canonical(
    (connections ?? [])
      .map((connection) => ({
        target: lower(connection.privateLinkServiceId),
        groups: (connection.groupIds ?? []).map((g) => g.toLowerCase()).sort(),
      }))
      .sort((a, b) => (a.target ?? "").localeCompare(b.target ?? "")),
  );

const toConnections = (
  name: string,
  connections: ReadonlyArray<PrivateLinkServiceConnectionSpec> | undefined,
) =>
  connections?.map((connection) => ({
    name: connection.name ?? name,
    properties: {
      privateLinkServiceId: connection.privateLinkServiceId,
      groupIds: connection.groupIds,
      requestMessage: connection.requestMessage,
    },
  }));

export const PrivateEndpointProvider = () =>
  Provider.succeed(PrivateEndpoint, {
    stables: [
      "privateEndpointName",
      "privateEndpointId",
      "resourceGroup",
      "location",
      "subnetId",
    ],

    list: Effect.fn(function* () {
      const { subscriptionId } = yield* AzureEnvironment.current;
      const page = yield* network
        .ListPrivateEndpointBySubscription({ subscriptionId })
        .pipe(
          Effect.flatMap((page) =>
            requireSinglePage("ListPrivateEndpointBySubscription", page),
          ),
        );
      return page.value.flatMap((endpoint) => {
        const group = resourceGroupOf(endpoint.id);
        return hasAnyAlchemyTag(endpoint.tags) &&
          group !== undefined &&
          endpoint.name !== undefined
          ? [toAttrs(group, endpoint.name, endpoint)]
          : [];
      });
    }),

    diff: Effect.fn(function* ({ news, olds, output }) {
      if (!isResolved(news) || output === undefined) return undefined;
      if (
        !sameId(news.resourceGroup, output.resourceGroup) ||
        (news.name !== undefined &&
          !sameId(news.name, output.privateEndpointName)) ||
        (news.location !== undefined &&
          !sameId(news.location, output.location)) ||
        !sameId(news.subnetId, output.subnetId) ||
        (olds !== undefined &&
          (connectionKey(news.privateLinkServiceConnections) !==
            connectionKey(olds.privateLinkServiceConnections) ||
            connectionKey(news.manualPrivateLinkServiceConnections) !==
              connectionKey(olds.manualPrivateLinkServiceConnections) ||
            news.customNetworkInterfaceName !==
              olds.customNetworkInterfaceName ||
            canonical(news.ipConfigurations ?? []) !==
              canonical(olds.ipConfigurations ?? [])))
      ) {
        return { action: "replace" } as const;
      }
      return undefined;
    }),

    read: Effect.fn(function* ({ id, olds, output }) {
      const { subscriptionId } = yield* AzureEnvironment.current;
      const resourceGroup = output?.resourceGroup ?? olds?.resourceGroup;
      if (resourceGroup === undefined) return undefined;
      const name =
        output?.privateEndpointName ??
        olds?.name ??
        (yield* createNetworkName(id, 64));
      const observed = yield* getEndpoint(subscriptionId, resourceGroup, name);
      if (observed === undefined) return undefined;
      const attrs = toAttrs(resourceGroup, name, observed);
      return (yield* isOwned(id, observed.tags)) ? attrs : Unowned(attrs);
    }),

    reconcile: Effect.fn(function* ({ id, news, output }) {
      const env = yield* AzureEnvironment.current;
      const { subscriptionId } = env;
      yield* ensureRegistered(subscriptionId, "Microsoft.Network");
      const resourceGroup = news.resourceGroup;
      const name =
        news.name ??
        output?.privateEndpointName ??
        (yield* createNetworkName(id, 64));
      const location = news.location ?? output?.location ?? env.location;
      const tags = yield* desiredTags(id, news.tags);
      const get = getEndpoint(subscriptionId, resourceGroup, name);

      // Observe.
      let observed = yield* get;

      // Ensure + sync. There is no tags PATCH: tags and application
      // security groups are synced with an idempotent PUT of the same
      // connections.
      if (
        observed === undefined ||
        tagsDiffer(observed.tags, tags) ||
        !sameSet(
          (observed.properties?.applicationSecurityGroups ?? []).flatMap(
            (asg) => (asg.id === undefined ? [] : [asg.id]),
          ),
          news.applicationSecurityGroupIds,
        )
      ) {
        yield* network
          .PrivateEndpointsCreateOrUpdate({
            subscriptionId,
            resourceGroupName: resourceGroup,
            privateEndpointName: name,
            location,
            tags,
            properties: {
              subnet: { id: news.subnetId },
              privateLinkServiceConnections: toConnections(
                name,
                news.privateLinkServiceConnections,
              ),
              manualPrivateLinkServiceConnections: toConnections(
                name,
                news.manualPrivateLinkServiceConnections,
              ),
              customNetworkInterfaceName: news.customNetworkInterfaceName,
              ipConfigurations: news.ipConfigurations?.map((config) => ({
                name: config.name,
                properties: {
                  groupId: config.groupId,
                  memberName: config.memberName,
                  privateIPAddress: config.privateIpAddress,
                },
              })),
              applicationSecurityGroups: news.applicationSecurityGroupIds?.map(
                (id) => ({ id }),
              ),
            },
          })
          .pipe(Effect.retry(whileNetworkBusy));
      }
      observed = yield* waitNetworkProvisioned(`private endpoint ${name}`, get);
      return toAttrs(resourceGroup, name, observed);
    }),

    delete: Effect.fn(function* ({ output }) {
      const { subscriptionId } = yield* AzureEnvironment.current;
      yield* ignoreNotFound(
        network.DeletePrivateEndpoint({
          subscriptionId,
          resourceGroupName: output.resourceGroup,
          privateEndpointName: output.privateEndpointName,
        }),
      ).pipe(Effect.retry(whileNetworkBusy));
      yield* waitNetworkGone(
        `private endpoint ${output.privateEndpointName}`,
        getEndpoint(
          subscriptionId,
          output.resourceGroup,
          output.privateEndpointName,
        ),
      );
    }),

    // Delete private endpoints before the subnets they live in.
    nuke: {
      dependsOn: [
        "Azure.Network.VirtualNetwork",
        "Azure.Network.Subnet",
        "Azure.Resources.ResourceGroup",
      ],
    },
  });
